### ISSUE TITLE
BlockUI Bug

### ISSUE THREAD

**Issue by pjrobertson** [iwillhappy1314/wenprise-wechatpay-checkout-for-woocommerce#2]
打开支付页面（`https://XXXX/checkout/order-pay/10066/?key=wc_order_pJuwNwhq6YFCv`) 每次刷新有一下bug 在游览器的console 里：

```
VM400:1 Uncaught SyntaxError: Unexpected identifier
    at p.blockUI (jquery.blockUI.min.js?ver=2.7.0-wc.6.4.1:formatted:24:13)
    at script.js?ver=1.0.10:1:106
    at script.js?ver=1.0.10:8:107
```
![Screen Region 2022-07-08 at 11 03 44](https://user-images.githubusercontent.com/150431/177908898-a47e3f44-d8c4-4413-ab78-c7c40f1d999b.png)

我们网站用的是Woocommerce 6.4.1, Wordpress 5.9.3, jQuery Blocks: `XXXX/wp-content/plugins/woocommerce/assets/js/jquery-blockui/jquery.blockUI.min.js?ver=2.7.0-wc.6.4.1`

希望能帮忙！

**Comment by iwillhappy1314** [comment]
支付流程已重构，此问题已不存在。
