### ISSUE TITLE
如何设置open_id

### ISSUE THREAD

**Issue by pjrobertson** [iwillhappy1314/wenprise-wechatpay-checkout-for-woocommerce#3]
官网说明不清楚。里面有说：

`微信端公众号支付，需要安装微信登录插件，设置 open_id`

微信登录插件从哪里下载并如何安装？

另外插件设置页面有提到去`「开发 > 开发配置」`来获得app ID / secrect 和 miniapp ID / secret，但是登录微信支付平台去这个页面，没有地方可以设置miniapp ID. 如何设置？miniapp ID/secret 功能是什么？
![Screen Region 2022-07-08 at 11 29 01](https://user-images.githubusercontent.com/150431/177911338-ed857bc9-6d67-42c0-9b6e-4b191b1766b2.png)

谢谢！

**Comment by zx900930** [comment]
对于普通网站来说其实只需要填上面appid和App secret两个值就够了.
也不一定要用小程序或公众号的, 企业微信也行.
但是能使用的前提是都需要通过**微信认证**
参见
AppID关联:
https://kf.qq.com/faq/1801116VJfua1801113QVNVz.html
AppID查询:
https://kf.qq.com/faq/181105JJNbmm181105eUZfee.html
如果你是企业微信用户App Secret在这里查:
https://developer.work.weixin.qq.com/document/path/90665#secret

**Comment by pjrobertson** [comment]
OK, 那就清楚。我把这个bug 关掉吧
