### ISSUE TITLE
手机端进行微信支付后，提示“订单状态为 已完成 -无法支付；如需帮助，请联系我们”

### ISSUE THREAD

**Issue by yarin-zhang** [iwillhappy1314/wenprise-wechatpay-checkout-for-woocommerce#4]
你好，我已经完成了微信支付的配置工作。

有一个问题，在手机端支付完毕后，会跳转回订单结算页面，并出现这个提示：“订单状态为 已完成 -无法支付；如需帮助，请联系我们”。不会跳转到“订单已接收”界面。

但在电脑支付都是正常的，桌面端可以回跳转到正常的“订单已接收”页面。

这个有办法解决吗？或者能够自定义这个通知也行的。

![Snipaste_2022-09-22_21-16-46](https://user-images.githubusercontent.com/58888890/191757314-2dd62e35-e2cd-4435-946c-f81f1892eff1.png)

**Comment by yarin-zhang** [comment]
我大致发现了问题出在哪里，环境是 iOS 16 和 Safari。

我描述下复现情况：
1. 在原订单页面 A 中点支付按钮时，会打开一个新的跳转界面。
2. 跳转到微信完成支付操作。
3. 跳转回 Safari，此时会打开一个错误提示订单页面 B，也就是上面提到的报错的页面。
4. 如果关掉订单页面 B，会发现订单页面 A 还保留着，A 是正常的“订单已接收”页面。

也就是说 A 按照电脑端的逻辑做了一次支付成功页的跳转。导致后打开的界面 B 再次访问这个页面时，认为用户重复支付了，所以会出现这个错误提示。

**Comment by iwillhappy1314** [comment]
支付流程已重构，此问题已不存在。
